#!/usr/bin/env bash
# Turn the flight sheet into miner.conf. Runs before every start.
#
# Flight sheet mapping:
#   Pool URL            -> CUSTOM_URL       stratum+tcp://host:port
#   Wallet/template     -> CUSTOM_TEMPLATE  <payout address>.<worker>
#   Password            -> CUSTOM_PASS      (TSC pools ignore it)
#   Extra config args   -> CUSTOM_USER_CONFIG, one KEY=VALUE per line:
#       MODEL_URL=https://host/Qwen3-8B-<commit>-bf16.gguf
#       MODEL_SHA256=<sha256>          strongly recommended
#       MODEL_PATH=/path/to/model.gguf if you already have it on the rig
#       MODEL_DIR=/hive-config/models  where to cache the download
#       SLOTS=, MEOW_GROUPS=, CTX=     leave unset: the miner auto-tunes per GPU
#       API_PORT=21550
[[ -z $CUSTOM_CONFIG_FILENAME ]] && echo "no CUSTOM_CONFIG_FILENAME" && exit 1
mkdir -p "$(dirname "$CUSTOM_CONFIG_FILENAME")"

conf="# generated by h-config.sh — edits are overwritten on next start
POOL_URL=${CUSTOM_URL}
WALLET=${CUSTOM_TEMPLATE}
PASSWORD=${CUSTOM_PASS:-x}
"
# Pass the user's KEY=VALUE lines through untouched, dropping comments/blanks.
if [[ -n $CUSTOM_USER_CONFIG ]]; then
  conf+="$(echo "$CUSTOM_USER_CONFIG" | sed -e 's/\r$//' -e '/^\s*#/d' -e '/^\s*$/d')
"
fi
echo "$conf" > "$CUSTOM_CONFIG_FILENAME"
