# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proof

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BatchValidation(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BatchValidation()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBatchValidation(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BatchValidation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BatchValidation
    def Shares(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from proof.BatchShare import BatchShare
            obj = BatchShare()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BatchValidation
    def SharesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BatchValidation
    def SharesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # BatchValidation
    def Chunk(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # BatchValidation
    def RankRatio(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BatchValidation
    def Bootstrap(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def BatchValidationStart(builder):
    builder.StartObject(4)

def Start(builder):
    BatchValidationStart(builder)

def BatchValidationAddShares(builder, shares):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(shares), 0)

def AddShares(builder, shares):
    BatchValidationAddShares(builder, shares)

def BatchValidationStartSharesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSharesVector(builder, numElems):
    return BatchValidationStartSharesVector(builder, numElems)

def BatchValidationAddChunk(builder, chunk):
    builder.PrependUint32Slot(1, chunk, 0)

def AddChunk(builder, chunk):
    BatchValidationAddChunk(builder, chunk)

def BatchValidationAddRankRatio(builder, rankRatio):
    builder.PrependFloat32Slot(2, rankRatio, 0.0)

def AddRankRatio(builder, rankRatio):
    BatchValidationAddRankRatio(builder, rankRatio)

def BatchValidationAddBootstrap(builder, bootstrap):
    builder.PrependUint32Slot(3, bootstrap, 0)

def AddBootstrap(builder, bootstrap):
    BatchValidationAddBootstrap(builder, bootstrap)

def BatchValidationEnd(builder):
    return builder.EndObject()

def End(builder):
    return BatchValidationEnd(builder)
