# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proof

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BatchShare(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BatchShare()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBatchShare(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BatchShare
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BatchShare
    def HashId(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # BatchShare
    def HashIdAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # BatchShare
    def HashIdLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BatchShare
    def HashIdIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # BatchShare
    def Request(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # BatchShare
    def RequestAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # BatchShare
    def RequestLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BatchShare
    def RequestIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def BatchShareStart(builder):
    builder.StartObject(2)

def Start(builder):
    BatchShareStart(builder)

def BatchShareAddHashId(builder, hashId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(hashId), 0)

def AddHashId(builder, hashId):
    BatchShareAddHashId(builder, hashId)

def BatchShareStartHashIdVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartHashIdVector(builder, numElems):
    return BatchShareStartHashIdVector(builder, numElems)

def BatchShareAddRequest(builder, request):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(request), 0)

def AddRequest(builder, request):
    BatchShareAddRequest(builder, request)

def BatchShareStartRequestVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartRequestVector(builder, numElems):
    return BatchShareStartRequestVector(builder, numElems)

def BatchShareEnd(builder):
    return builder.EndObject()

def End(builder):
    return BatchShareEnd(builder)
